fix(pontos): filter and process only transfer-related events (#137)
## Description

It fixes the indexing error that occurs with the pending blocks:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: PosOverflow }', 
``` 

## What type of PR is this? (check all applicable)
- [X] 🐛 Bug Fix (`fix:`)

## Added tests?
- [X] 🙋 no, because I need help

## Added to documentation?
- [X] 🙅 no documentation needed

![done](https://media2.giphy.com/media/R12GjfNoeaGNjTeget/giphy.gif)

## Closing Issues

- Fixes #135 will close issue 135 when the PR is merged.

---------

Co-authored-by: glihm <dev@glihm.net>